### PR TITLE
Db cluster support

### PR DESCRIPTION
**Pull request by wobeng**
tested

### CODE REVIEW

**Comment by stevemac007** [comment]
Thanks for contributing this - it looks like you've been through the trouble of running this against a real cluster. Thanks - saves me from needing to spin up a cluster.

Can you add a comment to the readme about adding cluster support and the setup you have tested this against?

**Comment by wobeng** [comment]
sorry for the closing it..it was a mistake...I will add the comments

**Comment by wobeng** [comment]
I added the comment. What do you mean by "setup you have tested this against"? I'm currently using it now on my production clusters

**Comment by stevemac007** [comment]
I have not used this with a cluster, so was just wondering if there was any specific setup needed to make this work.

Given your comments are to just tag one of the instances that should do.  What if I tag more than one? Will that create multiple backups at the same time? Will it error?

I feel it might - should the instructions be more explicitly clear that you should only tag one instance? Or does that not matter?

The code looks good, will give it one more review his morning and merge the change.

**Comment by wobeng** [comment]
good point on the possible multiple backup issues. I prevent it with the latest commit..Please test and update me

**Review by stevemac007 — APPROVED** [review]
I like this branch - I'll port over my tests later tonight to increase the test coverage like I had on the other branch.

**Comment by allaire** [comment]
@stevemac007 @wobeng Hi guys, was this commit tested or used in production? I just pulled master to setup this in our sandbox environment, and the setup script was failing right from the beginning because of invalid yaml (https://github.com/cevoaustralia/aws-backup-lambda/pull/8/files#diff-cb222d20613245c796d9ce29c4fb26a8R93)

**Comment by wobeng** [comment]
@allaire  you are right. I fixed this issues in my private repo but forgot to create a pull request

[link](https://github.com/wobeng/aws-backup-lambda/commit/9ccb79f8c41e1c109d2ca775bf31eb76775c579f)

**Comment by allaire** [comment]
Hi @wobeng,

I opened a pull request as well, thanks for confirming.

Curious, I just deployed using the script. Let say I now want to edit the config and change the `keep_count` value, how do I do that once it's already setup?

Also is there a way to trigger manually a backup?

**Comment by wobeng** [comment]
you can modify [cloudformation.yaml](https://github.com/wobeng/aws-backup-lambda/commit/480dc9f64d78928100aca407dc7af1504002b74d) and re deploy.

**Comment by allaire** [comment]
@wobeng Thanks, but I think that your `HourlyBackupEvent` is still running each 7 days (per the `rate(7 days)` attribute), unless I'm missing something?

**Comment by wobeng** [comment]
@allaire omg, you are right...I need to change that. you saved my butt.

**Pull request merged**
